# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='strategy.proto',
  package='strategy',
  syntax='proto3',
  serialized_pb=_b('\n\x0estrategy.proto\x12\x08strategy\"\x89\x01\n\nMarketTick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03\x62id\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x03 \x01(\x01\x12\x12\n\nlast_price\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x03\x12\x14\n\x0ctimestamp_ns\x18\x06 \x01(\x03\x12\x17\n\x0fportfolio_value\x18\x07 \x01(\x01\"\x8d\x01\n\rTradeDecision\x12.\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1e.strategy.TradeDecision.Action\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\x13\n\x0blimit_price\x18\x03 \x01(\x01\"%\n\x06\x41\x63tion\x12\x08\n\x04HOLD\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x32R\n\x0fTradingStrategy\x12?\n\x0cOnMarketData\x12\x14.strategy.MarketTick\x1a\x17.strategy.TradeDecision\"\x00\x42\x1cZ\x1asynthbull/pkg/gen/strategyb\x06proto3')
)



_TRADEDECISION_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='strategy.TradeDecision.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_TRADEDECISION_ACTION)


_MARKETTICK = _descriptor.Descriptor(
  name='MarketTick',
  full_name='strategy.MarketTick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='strategy.MarketTick.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bid', full_name='strategy.MarketTick.bid', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ask', full_name='strategy.MarketTick.ask', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_price', full_name='strategy.MarketTick.last_price', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='strategy.MarketTick.volume', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_ns', full_name='strategy.MarketTick.timestamp_ns', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portfolio_value', full_name='strategy.MarketTick.portfolio_value', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=166,
)


_TRADEDECISION = _descriptor.Descriptor(
  name='TradeDecision',
  full_name='strategy.TradeDecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='strategy.TradeDecision.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='strategy.TradeDecision.quantity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_price', full_name='strategy.TradeDecision.limit_price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRADEDECISION_ACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=310,
)

_TRADEDECISION.fields_by_name['action'].enum_type = _TRADEDECISION_ACTION
_TRADEDECISION_ACTION.containing_type = _TRADEDECISION
DESCRIPTOR.message_types_by_name['MarketTick'] = _MARKETTICK
DESCRIPTOR.message_types_by_name['TradeDecision'] = _TRADEDECISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarketTick = _reflection.GeneratedProtocolMessageType('MarketTick', (_message.Message,), dict(
  DESCRIPTOR = _MARKETTICK,
  __module__ = 'strategy_pb2'
  # @@protoc_insertion_point(class_scope:strategy.MarketTick)
  ))
_sym_db.RegisterMessage(MarketTick)

TradeDecision = _reflection.GeneratedProtocolMessageType('TradeDecision', (_message.Message,), dict(
  DESCRIPTOR = _TRADEDECISION,
  __module__ = 'strategy_pb2'
  # @@protoc_insertion_point(class_scope:strategy.TradeDecision)
  ))
_sym_db.RegisterMessage(TradeDecision)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\032synthbull/pkg/gen/strategy'))

_TRADINGSTRATEGY = _descriptor.ServiceDescriptor(
  name='TradingStrategy',
  full_name='strategy.TradingStrategy',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=312,
  serialized_end=394,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnMarketData',
    full_name='strategy.TradingStrategy.OnMarketData',
    index=0,
    containing_service=None,
    input_type=_MARKETTICK,
    output_type=_TRADEDECISION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADINGSTRATEGY)

DESCRIPTOR.services_by_name['TradingStrategy'] = _TRADINGSTRATEGY

# @@protoc_insertion_point(module_scope)
