# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import strategy_pb2 as strategy__pb2


class TradingStrategyStub(object):
  """The service definition for the trading strategy.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OnMarketData = channel.unary_unary(
        '/strategy.TradingStrategy/OnMarketData',
        request_serializer=strategy__pb2.MarketTick.SerializeToString,
        response_deserializer=strategy__pb2.TradeDecision.FromString,
        )


class TradingStrategyServicer(object):
  """The service definition for the trading strategy.
  """

  def OnMarketData(self, request, context):
    """OnMarketData is called when a new market tick is received.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TradingStrategyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OnMarketData': grpc.unary_unary_rpc_method_handler(
          servicer.OnMarketData,
          request_deserializer=strategy__pb2.MarketTick.FromString,
          response_serializer=strategy__pb2.TradeDecision.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'strategy.TradingStrategy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
